- docs/config/tech-docs.yml
> fix: changes to docs config to ensure css renders with docpath

- docs/config.rb
> fix: udpate docs config to use relative assets

- docs/config.rb
> fix: use relative asset with public build dir

- README.md
> fix: update root READme URL to tech docs

- monitoring-as-code/monitoring-config/src/dashboards/detail-dashboard.libsonnet
- monitoring-as-code/monitoring-config/src/dashboards/journey-dashboard.libsonnet
- monitoring-as-code/monitoring-config/src/dashboards/product-dashboard.libsonnet
- monitoring-as-code/monitoring-config/src/dashboards/summary-dashboard.libsonnet
> Fix: updated the environment templates for all dashboards to select sli_value

- .gitignore
- monitoring-as-code/run-mixin.sh
> 85 add underscore to output directory

- monitoring-as-code/deploy.sh
> Refactor: updating deploy.sh to use docker run

- monitoring-as-code/Dockerfile
- monitoring-as-code/run-mixin.sh
> updated dockerfile and run-mixin to include promtool

- monitoring-as-code/README.md
- monitoring-as-code/deploy.sh
> refactor: rename docker image name

- monitoring-as-code/deploy.sh
> Refactor: deploy script now copies output to corresponding local directories

- .github/workflows/docker-build-branch.yml
- .github/workflows/docker-build-tag.yml
- monitoring-as-code/Dockerfile
- monitoring-as-code/run-mixin.sh
> feat: pass mac_version var from gh workflow

- .github/dependabot.yml
> 32 configure dependabot scanning

- monitoring-as-code/src/dashboards/detail-dashboard.libsonnet
- monitoring-as-code/src/mac-config.libsonnet
> refactor: moved metric config into new metric categories object and updated config items to be defined locally then exported

- .github/release-drafter.yml
resolves #126 -  update the categories and labels based on conventional commit messages.
> refactor: update the categories and labels

- monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
- monitoring-as-code/src/mac-config.libsonnet
- monitoring-as-code/src/sli-elements/recording-rules.libsonnet
- monitoring-as-code/src/sli-metric-libraries/sli-availability-cloudwatch-alb.libsonnet
- monitoring-as-code/src/sli-metric-libraries/sli-availability-generic.libsonnet
- monitoring-as-code/src/sli-metric-libraries/sli-availability-promclient.libsonnet
- monitoring-as-code/src/sli-metric-libraries/sli-average-metric.libsonnet
- monitoring-as-code/src/sli-metric-libraries/sli-avgovertime-generic.libsonnet
- monitoring-as-code/src/sli-metric-libraries/sli-correctness-cloudwatch-sqs-dlq.libsonnet
- monitoring-as-code/src/sli-metric-libraries/sli-freshness-cloudwatch-sqs.libsonnet
- monitoring-as-code/src/sli-metric-libraries/sli-latency-cloudwatch-alb.libsonnet
- monitoring-as-code/src/sli-metric-libraries/sli-latency-promclient.libsonnet
- monitoring-as-code/src/sli-metric-libraries/sli-metric-library-template.libsonnet
- monitoring-as-code/src/util/sli-metric-library-functions.libsonnet
> 123 create average latency sli type

- monitoring-as-code/src/alerts/burn-rate-alerts.libsonnet
- monitoring-as-code/src/mac-config.libsonnet
> feat: added alert payload configuration item to mac config

- monitoring-as-code/src/sli-metric-config.libsonnet
> feat: added new metrics for rds read and write and sli types for average iops and throughput

- monitoring-as-code/src/dashboards/detail-dashboard-elements/cloudwatch-sqs.libsonnet
- monitoring-as-code/src/dashboards/detail-dashboard.libsonnet
> fix: detail dashboard config now uses metric type configs instead of sli types

- .github/workflows/docker-build-branch.yml
> refactor: add snyk steps to check docker image for vulnerabilities

- .github/workflows/docker-build-branch.yml
> fix: allow workflow to write packages to GHCR

- monitoring-as-code/mixin-defs/monitoring-mixin.jsonnet
> fix: replaced urls in monitoring mixin with localhost urls

- monitoring-as-code/src/dashboards/detail-dashboard-elements/cloudwatch-sqs.libsonnet
- monitoring-as-code/src/metric-types.libsonnet
- monitoring-as-code/src/sli-metric-libraries/sli-freshness-cloudwatch-sqs.libsonnet
> fix: correct sql metric naming and labels

- monitoring-as-code/src/dashboards/detail-dashboard-elements/http-requests-availability.libsonnet
> fix: http requests availability now works with just errorstatus or resource labels

- .github/release-drafter.yml
> refactor: add dependencies label to release drafter

- .github/workflows/docker-build-branch.yml
- .github/workflows/docker-build-tag.yml
> refactor: Update Docker Build Tag Workflow

- monitoring-as-code/src/dashboards/detail-dashboard-elements/cloudwatch-sqs.libsonnet
- monitoring-as-code/src/dashboards/detail-dashboard-elements/detail-dashboard-elements-template.libsonnet
- monitoring-as-code/src/dashboards/detail-dashboard-elements/http-requests-availability.libsonnet
- monitoring-as-code/src/dashboards/detail-dashboard-elements/http-requests-latency.libsonnet
- monitoring-as-code/src/metric-types.libsonnet
> refactor: giving target metrics for detail dashboard elements better names

- .github/workflows/docker-build-branch.yml
- monitoring-as-code/Dockerfile
- monitoring-as-code/run-mixin.sh
> refactor: add docker image scan to the workflow

- monitoring-as-code/README.md
> 187 update readme installation and useage instructions

- monitoring-as-code/mixin-defs/testing-mixin.jsonnet
> feat: added testing mixin

- monitoring-as-code/src/metric-types.libsonnet
> fix: fixed typo for aws sqs

- monitoring-as-code/mixin-defs/generic-mixin.jsonnet
- monitoring-as-code/mixin-defs/testing-mixin.jsonnet
- monitoring-as-code/src/metric-types.libsonnet
- monitoring-as-code/src/sli-value-libraries/generic-histogram-quantile-latency.libsonnet
- monitoring-as-code/src/sli-value-libraries/generic-proportion-of-errors-using-label.libsonnet
- monitoring-as-code/src/util/sli-value-library-functions.libsonnet
> feat: added sli value libraries for nginx generic approach

- .gitignore
> fix: added gitkeep to output directory and updated gitignore

- docs/source/features/index.html.md.erb
- docs/source/get-started/index.html.md.erb
> 185 document monitoring as code features

- .github/workflows/docker-build-branch.yml
> feat: add Hadolint Dockerfile linting tool

- local/README.md
- monitoring-as-code/README.md
> fix: correct git clone repo url

- monitoring-as-code/src/dashboards/summary-dashboard.libsonnet
> feat: add product view navigation to summary screen

- .github/workflows/docker-build-branch.yml
- monitoring-as-code/fmt.sh
- monitoring-as-code/lint.sh
> refactor: update workflow to use jsonnet fmt/lint container image

- monitoring-as-code/src/sli-value-libraries/average-freshness-using-queue-metric.libsonnet
Please note I also changed the changed sum to count in prometheus panel for consistency
resolves #264
> 264 freshness sli value denominator using wrong function

- monitoring-as-code/mixin-defs/testing-mixin.jsonnet
- monitoring-as-code/src/mixin-builder.libsonnet
> bug: rename stanza to journey1 in testing mixin

- monitoring-as-code/mixin-defs/testing-mixin.jsonnet
- monitoring-as-code/src/metric-types.libsonnet
> feat: modify sli for opensearch availability and latency

- docs/source/get-started/index.html.md.erb
- monitoring-as-code/mixin-defs/generic-mixin.jsonnet
- monitoring-as-code/mixin-defs/monitoring-mixin.jsonnet
- monitoring-as-code/mixin-defs/testing-mixin.jsonnet
- monitoring-as-code/src/mixin-builder.libsonnet
- monitoring-as-code/src/sli-value-libraries/average-freshness-using-queue-metric.libsonnet
- monitoring-as-code/src/sli-value-libraries/average-latency-using-seconds-target-metric.libsonnet
> 278 slitype refactoring to support distinct objects and consistent dominations 1

- .githooks/pre-commit
> Add hadolint into git pre-commit hooks

- .githooks/pre-commit
- monitoring-as-code/run-mixin.sh
> Add Shellcheck to pre-commit hooks

- .github/release-drafter.yml
> fix: change config docs to documentation

- .githooks/pre-commit
> Release 1.4.0

- .github/workflows/deploy-docs.yml
> feat: update deploy docs workflow to use official github actions

- monitoring-as-code/Dockerfile
> Update git version in Docker image.

- example-apps/sre-demo-java-app/README.md
- local/yace/config/config.yml
- monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
- monitoring-as-code/src/mixin-builder.libsonnet
> 274 add metric types label

- monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
> 326 generic product view template filtering

- .github/workflows/spellchecker.yml
> Add workflow dispatch trigger

- example-apps/localstack/README.md
- local/docker-compose.yaml
- local/yace/config/config.yml
- monitoring-as-code/src/metric-types.libsonnet
> Fix issues with YACE configuration

- monitoring-as-code/src/dashboards/overview-dashboard.libsonnet
> fix: change traffic duration

- monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
> 345 change panel colour when there is no sli data

- monitoring-as-code/mixin-defs/monitoring-mixin.jsonnet
- monitoring-as-code/mixin-defs/testing-mixin.jsonnet
- monitoring-as-code/src/metric-types.libsonnet
> feat: add-grafana-latency-and-sum-metrics and sli

- monitoring-as-code/src/metric-types.libsonnet
> fix: grafana detail view latency

- monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
- monitoring-as-code/src/dashboards/detail-dashboard.libsonnet
- monitoring-as-code/src/dashboards/journey-dashboard.libsonnet
- monitoring-as-code/src/dashboards/overview-dashboard.libsonnet
- monitoring-as-code/src/dashboards/product-dashboard.libsonnet
- monitoring-as-code/src/mac-config.libsonnet
> feat: add documentation panel to dashboards

- docs/config/tech-docs.yml
No current documentation on how to remove the footer. However the header is be fixed.
Fixes #365
> Change phase and header link

- .githooks/pre-push
> Optimise trufflehog pre-push scan.

- docs/source/get-started/install/index.html.md.erb
- monitoring-as-code/tools/spell-checker/dictionary.txt
> refractor: links to docs

- .github/workflows/scheduler-main.yml
> feat: add scheduler main workflow

- .github/workflows/deploy-docs.yml
resolves #384 
Successful run evidenced here https://github.com/michaelpearsonHO/sre-monitoring-as-code/actions/runs/3420822126
(no changes to drawio file made).
> fix: action render diagrams on all docs changes

- README.md
> docs: root readme dir structure update

- docs/README.md
> feat: add instructions to render diagrams locally

- monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
> refactor: hardcode colour black

- contributing.md
Documents our current release workflow for new contributors.
Read the new section in the contribution guide to see if it makes sense and ensure that no steps have been missed out.
> Add release workflow to contributing guide.

- monitoring-as-code/mixin-defs/generic-mixin.jsonnet
> refactor: update generic mixing file into golden sli category

- local/yace/config/config.yml
- monitoring-as-code/mixin-defs/generic-mixin.jsonnet
- monitoring-as-code/mixin-defs/testing-mixin.jsonnet
- monitoring-as-code/src/metric-types.libsonnet
create s3 storage sli.
Emulate the following data in localstack and you should see Prometheus sli05 being updated;
```
[
{
"MetricName": "5xxErrors",
"Value": 1
},
{
"MetricName": "4xxErrors",
"Value": 1
},
{
"MetricName": "TotalRequestLatency",
"Value": 1
},
{
"MetricName": "AllRequests",
"Value": 10
}
]
```
> create s3 storage sli

- .github/workflows/build-container-image.yml
- .github/workflows/feature.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
This pull request extracts some common logic that is re-used in the main, feature and release workflows into a shared workflow.
Fixes #413 
Note: When we migrate our repository into the UKHomeOffice Github organisation, we should re-visit our workflows to see if we can re-use some of the common workflows already available at https://github.com/UKHomeOffice/hocs-github-actions - Separate JIRA ticket has been created to track this.
The Github actions for main, feature and release workflows should pass. We have tested these on a separate repository [here](https://github.com/arifulhaqueHO/sre-monitoring-as-code/actions)
> Extract container building and testing into workflow.

- .github/workflows/main.yml
Fix broken main pipeline.
Main pipeline should succeed.
> Remove reference to incorrect workflow.

- contributing.md
To add a note on hotfix process for releasing.
Read the the contributing.md and make sure it makes sense.
> Add hotfix notes to contributing.md

- monitoring-as-code/Dockerfile
Fixes #448 
More info on issue
All snyk tests should pass.
> Fix: openssl vul

- monitoring-as-code/Dockerfile
update images in Dockerfile 
resolves #479 
build and run deploy scripts.
> update images in dockerfile

- SECURITY.md
- security.txt
Create security.md file as per the best practices 
read the security.md context file
> Create Security.md file

- monitoring-as-code/Dockerfile
> feat: bump git version

- .github/workflows/build-container-image.yml
- .github/workflows/feature.yml
_Describe the problem or feature in addition to a link to the issues when possible._
_Describe the how you would test this change._
> fix: correction to build container image workflow tag input vars

- .github/workflows/build-container-image.yml
- .github/workflows/main.yml
> fix: update synk workflow to use unqiue tag

- monitoring-as-code/mixin-defs/testing-mixin.jsonnet
- monitoring-as-code/src/metric-types.libsonnet
- monitoring-as-code/src/sli-value-libraries/proportion-of-errors-using-success-metric.libsonnet
> feat: add availability success library

- monitoring-as-code/mixin-defs/testing-mixin.jsonnet
- monitoring-as-code/run-mixin.sh
- monitoring-as-code/src/dashboards/dashboard-standard-elements.libsonnet
- monitoring-as-code/src/metric-types.libsonnet
- monitoring-as-code/src/mixin-builder.libsonnet
- monitoring-as-code/src/sli-value-libraries/availability-counter-using-1-failure-metric-for-num-and-1-total-metric-for-dem.libsonnet
- monitoring-as-code/src/sli-value-libraries/availability-counter-using-1-success-metric-for-num-and-1-total-metric-for-dem.libsonnet
- monitoring-as-code/src/sli-value-libraries/availability-counter-using-2-failure-metrics-for-num-and-1-total-metric-for-dem.libsonnet
- monitoring-as-code/src/sli-value-libraries/availability-counter-using-single-metric-for-both-num-and-dem-filtered-by-status-label.libsonnet
- monitoring-as-code/src/sli-value-libraries/availability-gauge-using-1-failure-metric-for-num-and-1-total-metric-for-dem.libsonnet
- monitoring-as-code/src/sli-value-libraries/availability-gauge-using-2-failure-metrics-for-num-and-3-metrics-dem.libsonnet
- monitoring-as-code/src/sli-value-libraries/availability-gauge-using-inservice-and-desired-instance-metrics.libsonnet
- monitoring-as-code/src/sli-value-libraries/availability-gauge-using-single-metric-for-both-num-and-dem.libsonnet
- monitoring-as-code/src/sli-value-libraries/availability-gauge-with-status-metric-and-integer-target.libsonnet
- monitoring-as-code/src/sli-value-libraries/correctness-gauge-for-queues-using-standard-and-dead-letter-queue-metrics.libsonnet
- monitoring-as-code/src/sli-value-libraries/freshness-gauge-for-queues-using-single-metric-and-secs-target.libsonnet
- monitoring-as-code/src/sli-value-libraries/latency-gauge-using-secs-metric-and-secs-target.libsonnet
- monitoring-as-code/src/sli-value-libraries/latency-histogram-quantile-using-bucket-metric-percentile-and-secs-target.libsonnet
- monitoring-as-code/src/sli-value-libraries/saturation-gauge-with-useage-metric-and-percent-target.libsonnet
> feat: add saturation gauge sli library

- monitoring-as-code/mixin-defs/testing-mixin.jsonnet
- monitoring-as-code/src/alerts/burn-rate-alerts.libsonnet
- monitoring-as-code/src/dashboards/overview-dashboard.libsonnet
- monitoring-as-code/src/mac-config.libsonnet
- monitoring-as-code/src/mixin-builder.libsonnet
> 618 add optional aws account metadata to grafana dashboard sli labels and prometheus alert rule labels

- monitoring-as-code/src/sli-value-libraries/availability-gauge-with-status-metric-and-integer-target.libsonnet
_Describe the problem or feature in addition to a link to the issues when possible._
_Describe the how you would test this change._
see SRE-1080 for more info
> fix: change ec2 avg success metric

- monitoring-as-code/src/alerts/burn-rate-alerts.libsonnet
- monitoring-as-code/src/metric-types.libsonnet
- monitoring-as-code/src/sli-value-libraries/availability-gauge-using-2-failure-metrics-for-num-and-1-total-metric-for-dem.libsonnet
- monitoring-as-code/src/sli-value-libraries/saturation-gauge-with-useage-metric-and-percent-target.libsonnet
> fix: correct alb metrics to use gauge promql functions

- monitoring-as-code/src/sli-value-libraries/availability-gauge-with-status-metric-and-integer-target.libsonnet
> fix: revert #644
